# Generated by Django 5.2.8 on 2025-12-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubcribers',
        ),
    ]
