# Generated by Django 5.2.8 on 2025-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_customuser_assigned_to_customuser_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariable',
            fields=[
                ('var_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('var_name', models.CharField(db_column='var_name', max_length=255, unique=True)),
                ('var_value', models.TextField(blank=True, db_column='var_value', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, db_column='datecreated')),
                ('lastupdated', models.DateTimeField(auto_now=True, db_column='lastupdated')),
            ],
            options={
                'verbose_name': 'Application Variable',
                'verbose_name_plural': 'Application Variables',
                'db_table': 'app_variables',
            },
        ),
    ]
