# Generated by Django 5.2.8 on 2025-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251119_1357'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='appvariable',
            name='isreadonly',
            field=models.IntegerField(db_column='isreadonly', default=0, editable=False),
        ),
    ]
