# Generated by Django 5.2.8 on 2025-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_appvariable_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvariable',
            name='isreadonly',
            field=models.IntegerField(db_column='readonly', default=0, editable=False),
        ),
    ]
