# Generated by Django 5.2.8 on 2025-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appvariable_isreadonly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appvariable',
            name='datecreated',
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='isreadonly',
            field=models.IntegerField(db_column='isreadonly', default=0, editable=False),
        ),
    ]
