# Generated by Django 5.2.8 on 2025-11-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_postcategory_clientstyle_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='ClientStyle',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
