# Generated by Django 5.2.8 on 2025-11-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_category_masterfield_widget_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('dynamic_content', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WidgetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('dynamic_content', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.widget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
