# Generated by Django 5.2.8 on 2025-11-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_categorypost_widgetpost_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Excerpt (Short Summary)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Main Content')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='subtitle for videos')),
                ('shortcodes', models.TextField(blank=True, null=True, verbose_name='short codes')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('btn_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Main Image')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video URL/Embed')),
                ('audio', models.URLField(blank=True, null=True, verbose_name='Audio URL/Embed')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Name/Class')),
                ('publish_now', models.BooleanField(default=False, verbose_name='Publish Now Checkbox')),
                ('image_align', models.CharField(blank=True, max_length=10, null=True, verbose_name='Image Alignment')),
                ('progress', models.IntegerField(blank=True, null=True, verbose_name='Progress Value')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('addfield1', models.TextField(blank=True, null=True, verbose_name='Add Field 1')),
                ('addfield2', models.TextField(blank=True, null=True, verbose_name='Add Field 2')),
                ('addfield3', models.TextField(blank=True, null=True, verbose_name='Add Field 3')),
                ('addfield4', models.TextField(blank=True, null=True, verbose_name='Add Field 4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author (User Who Created It)')),
            ],
            options={
                'verbose_name': 'Content Item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='categorypost',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MasterField',
        ),
        migrations.RemoveField(
            model_name='widgetpost',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='config',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='child_fields',
            field=models.JSONField(blank=True, default=list, help_text='Select the fields that content items (Posts) under this category will use.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='The parent category that dictates which fields are relevant for this post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.category'),
        ),
        migrations.DeleteModel(
            name='CategoryPost',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.DeleteModel(
            name='WidgetPost',
        ),
    ]
