# Generated by Django 5.2.8 on 2025-11-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_remove_categorypost_parent_delete_masterfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary for this category/section itself.', null=True),
        ),
    ]
