# Generated by Django 5.2.8 on 2025-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_post_options_remove_post_addfield1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
