# Generated by Django 5.2.8 on 2025-11-28 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_post_category_remove_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly version of the name. Used for client-facing website.', max_length=100, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description of this content type/category.', null=True)),
                ('child_fields', models.JSONField(blank=True, default=list, help_text='Fields enabled for child content items of this category.')),
            ],
            options={
                'verbose_name': 'Content Type (Category)',
                'verbose_name_plural': 'Content Types (Categories)',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('shortcodes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image_align', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=100, null=True)),
                ('btn_url', models.URLField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, help_text='A numeric value, e.g., for a progress bar.', null=True)),
                ('addfield1', models.CharField(blank=True, help_text='Add Field 1', max_length=255, null=True)),
                ('addfield2', models.CharField(blank=True, help_text='Add Field 2', max_length=255, null=True)),
                ('addfield3', models.CharField(blank=True, help_text='Add Field 3', max_length=255, null=True)),
                ('addfield4', models.CharField(blank=True, help_text='Add Field 4', max_length=255, null=True)),
                ('publish_now', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The parent category that dictates which fields are relevant for this post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.category')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['category', '-created_at'],
            },
        ),
    ]
