# Generated by Django 5.2.8 on 2025-11-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly version of the name. Used for client-facing website.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield1',
            field=models.CharField(blank=True, help_text='Custom Field 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield2',
            field=models.CharField(blank=True, help_text='Custom Field 2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield3',
            field=models.CharField(blank=True, help_text='Custom Field 3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield4',
            field=models.CharField(blank=True, help_text='Custom Field 4', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
