# Generated by Django 5.2.8 on 2025-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_category_slug_alter_post_addfield1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='btn_text',
            field=models.CharField(blank=True, default='Read More', max_length=100, null=True),
        ),
    ]
