# Generated by Django 5.2.8 on 2025-12-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_post_audio_alter_post_image_align_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_now',
        ),
    ]
