# Generated by Django 5.2.8 on 2025-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_post_publish_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_now',
            field=models.BooleanField(default=False),
        ),
    ]
