# Generated by Django 5.2.8 on 2025-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_post_publish_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order'], 'verbose_name': 'Post Gallery Image', 'verbose_name_plural': 'Post Gallery Images'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image_align',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
