# Generated by Django 5.2.8 on 2025-12-02 10:16

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_postimage_options_alter_post_image_align'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_now',
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Uncheck for Draft status. Check to make the content public.', verbose_name='Publish Live'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly version of the name.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='addfield4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.category'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=users.models.cat_image_upload_path),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first (0 is typically the primary image).'),
        ),
    ]
