# Generated by Django 5.2.8 on 2025-12-03 07:39

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_post_image_remove_post_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='widget_videos/')),
                ('child_fields', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Widget Type',
                'verbose_name_plural': 'Widget Types',
            },
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='category_videos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('shortcodes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_featured_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image_align', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_text', models.CharField(blank=True, default='Read More', max_length=100, null=True)),
                ('btn_url', models.URLField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('addfield1', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield2', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield3', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield4', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.category')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.cat_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.categorypost')),
            ],
            options={
                'verbose_name': 'Post Gallery Image',
                'verbose_name_plural': 'Post Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WidgetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('shortcodes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='widget_featured_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image_align', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_text', models.CharField(blank=True, default='Read More', max_length=100, null=True)),
                ('btn_url', models.URLField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('addfield1', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield2', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield3', models.CharField(blank=True, max_length=255, null=True)),
                ('addfield4', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.widget')),
            ],
            options={
                'verbose_name': 'Widget Content Item',
                'verbose_name_plural': 'Widget Content Items',
                'ordering': ['widget', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.wid_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.widgetpost')),
            ],
            options={
                'verbose_name': 'Widget Gallery Image',
                'verbose_name_plural': 'Widget Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
