# Generated by Django 5.2.8 on 2025-12-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_widget_remove_postimage_post_category_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='video',
        ),
        migrations.AddField(
            model_name='category',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='category_media/'),
        ),
        migrations.AddField(
            model_name='widget',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='widget_media/'),
        ),
    ]
