# Generated by Django 5.2.8 on 2025-12-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_category_video_remove_widget_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetpost',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='widgetpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='widgetpostimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.DeleteModel(
            name='WidgetPost',
        ),
        migrations.DeleteModel(
            name='WidgetPostImage',
        ),
    ]
