# Generated by Django 5.2.8 on 2025-12-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_widgetpost_widget_remove_widgetpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cat_posts_image/'),
        ),
        migrations.DeleteModel(
            name='CategoryPostImage',
        ),
    ]
