# Generated by Django 5.2.8 on 2025-12-16 07:25

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_categorypost_icon_alter_categorypost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='widget_media/')),
                ('child_fields', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorypost',
            options={'ordering': ['category', '-created_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='child_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.cat_post_upload_path),
        ),
        migrations.CreateModel(
            name='WidgetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.wid_post_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_posts', to='users.widget')),
            ],
            options={
                'ordering': ['widget', '-created_at'],
            },
        ),
    ]
