# Generated by Django 5.2.8 on 2025-12-16 07:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_widget_alter_categorypost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetpost',
            name='addfield1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='addfield2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='addfield3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='addfield4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='btn_text',
            field=models.CharField(blank=True, default='Read More', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='btn_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='image_align',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='shortcodes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='widgetpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.cat_post_upload_path),
        ),
    ]
