# Generated by Django 5.2.8 on 2025-12-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_widgetpost_addfield1_widgetpost_addfield2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='category_media/{category}/'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='widget_media/{widet}/'),
        ),
    ]
