# Generated by Django 5.2.8 on 2025-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_category_media_file_alter_widget_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/{category}/'),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/{widget}/'),
        ),
    ]
