# Generated by Django 5.2.8 on 2025-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_categorypost_video_alter_widgetpost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='media/{{ category }}/icons/'),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/{{ category }}/'),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='media/icons/'),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/{{ widget }}/'),
        ),
    ]
