# Generated by Django 5.2.8 on 2025-12-18 20:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_categorypost_icon_alter_categorypost_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.wid_post_upload_path),
        ),
    ]
