# Generated by Django 5.2.8 on 2025-12-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_widgetpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='cat_post_icons/'),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cat_post_video/'),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='wid_post_icons/'),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='wid_post_video/'),
        ),
    ]
