# Generated by Django 5.2.8 on 2025-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_categorypost_icon_alter_categorypost_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
