# Generated by Django 5.2.8 on 2025-12-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_categorypost_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='icon',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='widgetpost',
            name='icon',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
