# Generated by Django 5.2.8 on 2025-12-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_categorypost_icon_alter_widgetpost_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='name',
            new_name='title',
        ),
    ]
