# Generated by Django 5.2.8 on 2025-12-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_name_category_title_rename_name_widget_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubcribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
