# Generated by Django 5.2.8 on 2025-12-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_emailsubcribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubcribers',
        ),
    ]
