# Generated by Django 5.2.8 on 2025-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_delete_emailsubcribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appvariable',
            options={},
        ),
        migrations.RemoveField(
            model_name='appvariable',
            name='var_id',
        ),
        migrations.AddField(
            model_name='appvariable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='isreadonly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='var_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='var_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='appvariable',
            table=None,
        ),
    ]
