# Generated by Django 5.2.8 on 2025-12-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_appvariable_options_remove_appvariable_var_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Wants Newsletters'),
        ),
        migrations.AlterField(
            model_name='appvariable',
            name='var_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='racial_info',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_assign_staff',
            field=models.BooleanField(default=False, verbose_name='Can Assign Staff (Manager)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_create_user',
            field=models.BooleanField(default=False, verbose_name='Can Create Users'),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'Everyone'), ('staff_only', 'All Company Staff'), ('clients_only', 'Registered Clients Only'), ('subscribers_only', 'External Subscribers Only'), ('targeted', 'Specific Selection')], default='all', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_managers', models.ManyToManyField(blank=True, limit_choices_to={'role__can_assign_staff': True}, related_name='news_managed', to=settings.AUTH_USER_MODEL)),
                ('target_roles', models.ManyToManyField(blank=True, to='users.role')),
                ('target_users', models.ManyToManyField(blank=True, related_name='news_specific', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Broadcast',
                'ordering': ['-created_at'],
            },
        ),
    ]
