# Generated by Django 5.2.8 on 2025-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_externalsubscriber_remove_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Leave blank to send immediately upon publishing. Set a future date to schedule.', null=True),
        ),
    ]
