# Generated by Django 5.2.8 on 2025-12-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_newspost_last_sent_at_newspost_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Leave blank to use the system default email.', max_length=255, null=True),
        ),
    ]
