# Generated by Django 5.2.8 on 2025-12-26 21:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_newspost_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='sender_email',
            field=models.EmailField(blank=True, default=users.models.get_default_sender, help_text='Leave blank to use the system default email.', max_length=255, null=True),
        ),
    ]
