# Generated by Django 5.2.8 on 2025-12-26 23:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_newspost_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='sender_email',
            field=models.EmailField(blank=True, default=users.models.get_default_sender, max_length=255, null=True),
        ),
    ]
