# Generated by Django 5.2.8 on 2025-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_newspost_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('staff_only', 'All Company Staff'), ('targeted', 'Specific Selection')], default='all', max_length=20),
        ),
    ]
