# Generated by Django 5.2.8 on 2025-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_customuser_is_manager_alter_newspost_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('staff_only', 'All Company Staff'), ('subscribers_only', 'External Subscribers Only'), ('targeted', 'Specific Selection')], default='all', max_length=20),
        ),
    ]
