# Generated by Django 5.2.8 on 2025-12-27 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_department_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending...'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='target_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_manager': True}, related_name='news_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
