# Generated by Django 5.2.8 on 2025-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_newspost_status_alter_newspost_target_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Audience'), ('staff_only', 'Staff Only'), ('external_only', 'External Subscribers Only'), ('clients', 'Company Users (Clients)'), ('super_admin', 'Super Admins Only'), ('is_manager', 'Managers Only'), ('administrator', 'Administrators Only')], default='all', max_length=50),
        ),
    ]
