# Generated by Django 5.2.8 on 2025-12-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='target_managers',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='target_roles',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='target_users',
        ),
    ]
