# Generated by Django 5.2.8 on 2025-12-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_newspost_subject_alter_newspost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='subject',
            field=models.CharField(blank=True, help_text='Actual Email Subject Line', max_length=255),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(help_text='Internal Title (for your records)', max_length=255),
        ),
    ]
