# Generated by Django 5.2.8 on 2025-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_newspost_subject_alter_newspost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='widget_media/{widget}/'),
        ),
    ]
