# Generated by Django 5.2.8 on 2025-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_department_options_department_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending...'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=15),
        ),
    ]
