# Generated by Django 5.2.8 on 2025-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_newspost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='subject',
            field=models.CharField(blank=True, help_text='Email Subject Line', max_length=255),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(help_text='Internal Title', max_length=255),
        ),
    ]
