# Generated by Django 5.2.8 on 2025-12-30 20:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_newspost_subject_alter_newspost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='sender_email',
            field=models.EmailField(blank=True, default=users.models.get_default_sender, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
