# Generated by Django 5.2.8 on 2025-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_newspost_options_remove_newspost_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
