"""
Django settings for BGTECH project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7+ok!u*d0s#n!ida$djxkjm-*=u4_r822)(&l+qkm-$ezx9h*g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django_summernote',
    'users.apps.UsersConfig',
    'portech.apps.PortechConfig',
    'widget_tweaks',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BGTECH.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.app_settings_processor',
            ]
        },
    },
]

WSGI_APPLICATION = 'BGTECH.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'CUSTOMDASHBOARD',  # <-- Change this to the database you created in phpMyAdmin
#         'USER': 'root',                # Default XAMPP MySQL username
#         'PASSWORD': '',                # Default XAMPP MySQL password (empty string)
#         'HOST': '127.0.0.1',           # Or 'localhost'
#         'PORT': '3306',                # Default MySQL port
#         # Optional: Add OPTIONS for strict SQL mode if you encounter issues
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
#         }
#     }
# }

# DATABASES = {
#     'default': dj_database_url.config(
#         # This reads the DATABASE_URL environment variable on Render
#         default=os.environ.get('DATABASE_URL')
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_URL = '/bg-admin/login/'
LOGOUT_REDIRECT_URL = '/bg-admin/login/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# ⚡️ CRITICAL ADDITION: Use Custom Email Backend ⚡️
AUTHENTICATION_BACKENDS = [
    # 1. Your custom backend for email authentication (defined in users/backends.py)
    # 'users.backends.EmailBackend', 
    
    # 2. Default backend for checking permissions (is_staff, is_superuser)
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = '/static/' 

# STATICFILES_DIRS = [
# os.path.join(BASE_DIR, 'static'),
# ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



X_FRAME_OPTIONS = 'SAMEORIGIN' # Required for Summernote's iframe
SUMMERNOTE_THEME = 'bs5'  # Uses Bootstrap 4 styling

SUMMERNOTE_CONFIG = {
    'iframe': {
        'height': '100%', 
        'width': '100%',
    },
    
    'summernote': {
        'width': '100%', 
        'styleWithSpan': False,
        'bodyClass': 'summernote-editable-area', 
    },
    
    'codemirror': {
        'lineWrapping': True,     # Ensures horizontal wrapping is ON
        'lineNumbers': False,    # Optional: Disables line numbering
    },
    
    # # Optional: If the above doesn't work, this targets the standard
    # # Summernote behavior for ensuring content fits.
    # 'toolbar': [
    #     # Example of keeping a toolbar, this is the default
    #     ['style', ['style']],
    #     ['font', ['bold', 'italic', 'underline', 'clear']],  
    #     ['para', ['ul', 'ol', 'paragraph']],
    #     ['insert', ['link', 'hr', 'link', 'picture', 'video']], # Image support
    #     ['view', ['fullscreen', 'codeview', 'help']],
    # ],

}



# Replace 'localhost' with your Redis server address if different
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' # Or your local timezone
CELERY_BEAT_SCHEDULE = {
    'check-scheduled-broadcasts-every-minute': {
        'task': 'users.tasks.check_scheduled_broadcasts',
        'schedule': crontab(minute='*'),  # Runs every minute
    },
}
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465               # Changed to 587 when using TSL
EMAIL_USE_TLS = False          # Changed from True
EMAIL_USE_SSL = True           # Changed from False
EMAIL_HOST_USER = '{{ OFFICIAL_EMAIL }}'
EMAIL_HOST_PASSWORD = 'qnvtlryfopznwmnp'
# DEFAULT_FROM_EMAIL = '{{ OFFICIAL_EMAIL }}'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,

#     'formatters': {
#         'verbose': {
#             'format': '[{asctime}] {levelname} {name} | {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },

#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#     },

#     'loggers': {
#         # Django internal logs
#         'django': {
#             'handlers': ['console'],
#             'level': 'INFO',
#             'propagate': False,
#         },

#         # Celery worker logs
#         'celery': {
#             'handlers': ['console'],
#             'level': 'INFO',
#             'propagate': False,
#         },

#         # Your users app (broadcast system)
#         'users': {
#             'handlers': ['console'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#     },

#     'root': {
#         'handlers': ['console'],
#         'level': 'INFO',
#     },
# }
    
